apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
  namespace: netflix-deployment-ns
spec:
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix-container
        image: mrueda020/netflix-react-clone:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          
        
