apiVersion: v1
kind: Service
metadata:
  name: netflix_service
  namespace: netflix-deployment-ns
spec:
  selector:
    app: netflix
  ports:
  - port: 80
    targetPort: 80
    protocol: 'TCP'
  type: LoadBalancer  
