---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.example.com
  resources:
  - netflixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.example.com
  resources:
  - netflixes/finalizers
  verbs:
  - update
- apiGroups:
  - web.example.com
  resources:
  - netflixes/status
  verbs:
  - get
  - patch
  - update
